#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jenkins"
name = "Jenkins"
description.en = "Extendable continuous integration server"
description.fr = "Serveur d'intégration continue extensible"

version = "2.426.3~ynh2"

maintainers = ["yalh76"]

[upstream]
license = "MIT"
website = "https://jenkins.io"
userdoc = "https://www.jenkins.io/doc/book/"
code = "https://github.com/jenkinsci/jenkins"
cpe = "cpe:2.3:a:cloudbees:jenkins"
fund = "https://www.jenkins.io/donate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jenkins"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
    [resources.sources.jenkins-plugin-manager]
    url = "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.12.8/jenkins-plugin-manager-2.12.8.jar"
    sha256 = "e5b22868c498c311ea1b776e9087af199b795ddbf0bc0474b0b4ca9e67837f26"
    format = "whatever"
    extract = false
    rename = "jenkins-plugin-manager.jar"

    [resources.sources.main]
    url = "https://pkg.jenkins.io/debian-stable/binary/jenkins_2.426.3_all.deb"
    sha256 = "7a453125a0194deba5a6464220e8beab3d0cd6a83f84f85a096babfaf5e752b5"
    format = "whatever"
    extract = false
    rename = "jenkins.deb"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    github_webhook.url = "/github-webhook"
    github_webhook.allowed = "visitors"
    github_webhook.protected = false
    github_webhook.show_tile = false

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "openjdk-11-jdk|openjdk-17-jdk|openjdk-21-jdk",
        "daemon",
        "net-tools"
    ]
